#! /bin/sh

dunst &
sxhkd &
picom &
$HOME/.fehbg
$HOME/.config/polybar/launch.sh

# Make sure primary monitor is the first one, independent of physical position
$HOME/.config/bspwm/enforce_monitor_position.sh &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colours
bspc config focused_border_color '#6696b7'
bspc config active_border_color '#4a7b9d'
bspc config normal_border_color '#e6e8ef'

# Rules
bspc rule -a discord state=floating

# Run non-systemd autostart stuff
dex -a
